# Generated by Django 5.1.7 on 2025-11-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_schoolinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinfo',
            name='classes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='sciences_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
