# Generated by Django 5.1.7 on 2025-11-20 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_schoolinfo_classes_count_schoolinfo_sciences_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Raqam faqat '+' belgisi va raqamlardan iborat bo'lishi kerak.", regex='^\\+?\\d{7,15}$')])),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
