# Generated by Django 5.1.7 on 2025-11-20 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_connectschool'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConnectSchool',
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Raqam faqat '+' belgisi va raqamlardan iborat bo'lishi kerak.", regex='^\\+?\\d{7,15}$')]),
        ),
    ]
