# Generated by Django 5.1.7 on 2025-11-20 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_delete_connectschool_schoolinfo_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
            ],
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=155),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='science',
            field=models.CharField(max_length=155),
        ),
        migrations.AddField(
            model_name='teacher',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='mysite.category'),
        ),
    ]
