# Generated by Django 5.1.7 on 2025-11-20 15:37

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_alter_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinfo',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='UZ'),
        ),
    ]
