# Generated by Django 5.1.7 on 2025-11-21 02:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_alter_schoolinfo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Raqam faqat '+' belgisi, raqam va bo'shliqlardan iborat bo'lishi kerak.", regex='^\\+?\\d[\\d\\s]{6,20}$')]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
