# Generated by Django 5.1.7 on 2025-11-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_alter_schoolinfo_phone_alter_teacher_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='science',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
