# Generated by Django 5.1.7 on 2025-11-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_remove_teacher_science_alter_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='surname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
