# Generated by Django 5.1.7 on 2025-11-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_teacher_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='lavozim',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='surname',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
