# Generated by Django 5.1.7 on 2025-11-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_teacher_lavozim_alter_teacher_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
