# Generated by Django 5.1.7 on 2025-11-21 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_alter_teacher_surname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolinfo',
            old_name='sciences_count',
            new_name='subjects_count',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='lavozim',
            new_name='position',
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Номер телефона может содержать только '+', цифры и пробелы.", regex='^\\+?\\d[\\d\\s]{6,20}$')]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(upload_to='teachers/'),
        ),
    ]
