# Generated by Django 5.1.7 on 2025-11-21 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_rename_sciences_count_schoolinfo_subjects_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolinfo',
            old_name='subjects_count',
            new_name='sciences_count',
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Raqam faqat '+' belgisi, raqam va bo'shliqlardan iborat bo'lishi kerak.", regex='^\\+?\\d[\\d\\s]{6,20}$')]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
