# Generated by Django 5.1.7 on 2025-11-21 16:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_rename_subjects_count_schoolinfo_sciences_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='classes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Sinflar soni'),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Maktab email adresi'),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Raqam faqat '+' belgisi, raqam va bo'shliqlardan iborat bo'lishi kerak.", regex='^\\+?\\d[\\d\\s]{6,20}$')], verbose_name='Maktab telefon raqami'),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='sciences_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Fanlar soni'),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='students_count',
            field=models.PositiveIntegerField(default=0, verbose_name="O'quvchilar soni"),
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='teachers_count',
            field=models.PositiveIntegerField(default=0, verbose_name="O'qituvchilar soni"),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='mysite.category', verbose_name='Ustozlar guruhi'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=155, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lavozim'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Familiya'),
        ),
    ]
