# Generated by Django 5.1.7 on 2025-11-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0018_alter_news_description_alter_news_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('rahbariyat', 'Rahbariyat'), ('fan', "Fan o'qituvchisi"), ('boshlangich', "Boshlang'ich sinf o'qituvchisi")], max_length=50, unique=True),
        ),
    ]
