# Generated by Django 5.1.7 on 2025-11-23 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0020_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.category', verbose_name='Ustozlar guruhi'),
        ),
    ]
