# Generated by Django 5.1.7 on 2025-11-24 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0021_alter_teacher_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='position',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='mysite.category', verbose_name='Ustozlar guruhi'),
        ),
    ]
